export enum LicensingRegulatoryBody {
  CAC_CERTIFICATE = 'CAC_CERTIFICATE',
  ESVARBON = 'ESVARBON',
  LASRERA = 'LASRERA',
  NIESV = 'NIESV',
  QSHELTER_TRAINING_CERTIFICATE = 'QSHELTER_TRAINING_CERTIFICATE',
}
